(function(){'use strict';
const ID='r2-existing-files-sync';let busy=false;
function tr(){const en=String(document.documentElement.lang||navigator.language).toLowerCase().startsWith('en');return en?{title:'Import existing R2 files',desc:'Read objects uploaded to R2 outside ImgBed and add them to file management.',channel:'Channel name',prefix:'Directory prefix (optional)',overwrite:'Overwrite existing metadata',start:'Start import',working:'Importing…',scanned:'Scanned',imported:'Imported',skipped:'Skipped',done:'R2 synchronization completed.',failed:'Synchronization failed: ',confirm:'Existing metadata may be overwritten. Continue?'}:{title:'同步 R2 已有文件',desc:'读取通过 S3、Rclone 或控制台导入当前 R2 Bucket 的对象，并补录到文件管理中。',channel:'渠道名称',prefix:'目录前缀（可选）',overwrite:'覆盖已有元数据',start:'开始同步',working:'正在同步…',scanned:'已扫描',imported:'已导入',skipped:'已跳过',done:'R2 同步完成。',failed:'同步失败：',confirm:'这可能覆盖 ImgBed 中已有的文件元数据，确定继续吗？'}}
function report(t,n,s=''){return`${t.scanned} ${n.scanned} · ${t.imported} ${n.imported} · ${t.skipped} ${n.skipped}${s?` · ${s}`:''}`}
async function sync(el){if(busy)return;const t=tr(),channelName=el.querySelector('[name=r2-channel]').value.trim()||'R2_env',prefix=el.querySelector('[name=r2-prefix]').value.trim(),overwrite=el.querySelector('[name=r2-overwrite]').checked;if(overwrite&&!confirm(t.confirm))return;const button=el.querySelector('button'),status=el.querySelector('[role=status]'),total={scanned:0,imported:0,skipped:0};let cursor=null;busy=true;button.disabled=true;button.textContent=t.working;try{do{const response=await fetch('/api/manage/sync/r2',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({channelName,prefix,overwrite,cursor,limit:500})}),result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||`HTTP ${response.status}`);total.scanned+=result.scanned||0;total.imported+=result.imported||0;total.skipped+=result.skipped||0;cursor=result.truncated?result.cursor:null;status.className='r2-sync-status';status.textContent=report(t,total,t.working)}while(cursor);status.className='r2-sync-status is-success';status.textContent=report(t,total,t.done)}catch(error){status.className='r2-sync-status is-error';status.textContent=report(t,total,t.failed+error.message)}finally{busy=false;button.disabled=false;button.textContent=t.start}}
function panel(channelName){const t=tr(),el=document.createElement('section');el.id=ID;el.className='r2-sync-card';el.innerHTML=`<div class="r2-sync-heading"><span class="r2-sync-icon">R2</span><div><h3>${t.title}</h3><p>${t.desc}</p></div></div><div class="r2-sync-fields"><label><span>${t.channel}</span><input name="r2-channel" value="${channelName.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}" autocomplete="off"></label><label><span>${t.prefix}</span><input name="r2-prefix" placeholder="photos/" autocomplete="off"></label><label class="r2-sync-check"><input type="checkbox" name="r2-overwrite"><span>${t.overwrite}</span></label><button type="button">${t.start}</button></div><p class="r2-sync-status" role="status" aria-live="polite"></p>`;el.querySelector('button').addEventListener('click',()=>sync(el));return el}
function mount(){if(!location.pathname.startsWith('/systemConfig')||location.hash!=='#upload')return;const t=tr();document.querySelectorAll('.upload-settings .channel-card.cfr2').forEach(card=>{if(card.dataset.r2SyncAttached)return;card.dataset.r2SyncAttached='true';const button=document.createElement('button');button.type='button';button.className='r2-sync-entry';button.textContent=t.start;button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();document.getElementById(ID)?.remove();const channelName=card.querySelector('.channel-name')?.textContent.trim()||'R2_env',el=panel(channelName),cards=card.closest('.channel-cards');cards.parentNode.insertBefore(el,cards.nextSibling)});(card.querySelector('.card-actions')||card).appendChild(button)})}
new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});addEventListener('hashchange',mount);addEventListener('popstate',mount);mount()
}());
